### PR TITLE
update to a cutting edge version

### PR DESCRIPTION
**Pull request by jamesgorrie**

### CODE REVIEW

**Review by alfraser86 — APPROVED** [review]

**Comment by jamesgorrie** [comment]
Tested and run it - all seems to work?

**Comment by jamesgorrie** [comment]
Is this meant to be built anywhere?

**Comment by jamesgorrie** [comment]
@alfraser86 ^

**Comment by alfraser86** [comment]
@jamesgorrie Interesting question about when we remove repos as this isn't built anywhere and isn't really supported.

**Comment by alfraser86** [comment]
it was purely a test project

**Pull request merged**
